32 selection sort subtask of 12
AUC-SWE-Team-SCRUMptious/DSA_Visualizer pull request #42
Opened 2023-11-04 23:15 UTC by BavlyRemon

Created the Selection sort subtask along with driver code to test and validate its functionality by running a few test cases and printing the outputs.

2023-11-04 23:28 UTC, OmarElfouly requested changes
Shoul be good after documenting your test cases

2023-11-04 23:28 UTC, OmarElfouly commented on app/src/main/java/com/scrumptious/algorithmvisualizer/SelectionSortSequenceGen.kt
Try adding some the result of some of your tests to the bottom of the file as comments

2023-11-04 23:28 UTC, OmarElfouly commented on app/src/main/java/com/scrumptious/algorithmvisualizer/SelectionSortSequenceGen.kt
> +fun main() {
Comment this out please.

2023-11-04 23:52 UTC, OmarElfouly requested changes

2023-11-04 23:52 UTC, OmarElfouly commented on app/src/main/java/com/scrumptious/algorithmvisualizer/SelectionSortSequenceGen.kt
> +fun selectionSortSequenceGenerator(arr: Array<Int>): Array<Pair<Array<Int>, Array<Int>>> {
This needs the result attribute in order to be consistent with the Class Diagram

2023-11-05 00:18 UTC, iRustom commented
Looks good!

2023-11-05 00:18 UTC, merged